# Generated by Django 4.2.3 on 2023-07-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(default='', max_length=20, verbose_name='Telefono')),
                ('mail', models.CharField(default='', max_length=60, verbose_name='Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=15, verbose_name='Fecha de prestamo')),
                ('fechaposdev', models.CharField(max_length=15, verbose_name='Fecha posible de devolucion')),
                ('fechadev', models.CharField(max_length=15, verbose_name='Fecha de devolucion')),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementos.persona')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementos.elemento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementos.estado')),
            ],
        ),
    ]
